// <auto-generated />
namespace OPGPROJECT_OPG.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class lvel2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lvel2));
        
        string IMigrationMetadata.Id
        {
            get { return "201911021551471_lvel2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
