// <auto-generated />
namespace OPGPROJECT_OPG.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addusermodal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addusermodal));
        
        string IMigrationMetadata.Id
        {
            get { return "201910220643576_add-user-modal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
